sudo: false
language: python
cache: pip
os: linux
dist: trusty

matrix:
  include:
  - python: "2.7"
  - python: "3.3"
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "pypy"
  - python: "pypy3"
  - python: "3.7"
    # Python 3.7 requires special handling in Travis CI for now:
    dist: xenial
    sudo: required
    before_script:
      # Add an IPv6 config - see the corresponding Travis issue
      # https://github.com/travis-ci/travis-ci/issues/8361#issuecomment-350497804
      - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
          sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
        fi

# command to install dependencies
install:
  - python setup.py install
  - pip install pytest coverage coveralls
script:
  - ./runtests.sh
after_success:
  - coveralls
notifications:
  email: false
  slack: friendsofhasgeek:3bLViYSzhfaThJovFYCVD3fX
