language: python
python:
  - 3.7
  - 3.8
  - 3.9
  - 3.10

# command to install dependencies
install:
  - python setup.py install
  - pip install pytest coverage coveralls
script:
  - ./runtests.sh
after_success:
  - coveralls
notifications:
  email: false
