sudo: false
language: python
cache: pip
os: linux
dist: trusty

matrix:
  include:
  - python: "2.7"
  - python: "3.6"
  - python: "3.7"

# command to install dependencies
install:
  - python setup.py install
  - pip install pytest coverage coveralls
script:
  - ./runtests.sh
after_success:
  - coveralls
notifications:
  email: false
  slack: friendsofhasgeek:3bLViYSzhfaThJovFYCVD3fX
